# Плагин создан для праздничных ивентов
# Разработчик: Soldin.jar

enabled: true

# Интервал смены текста (в секундах)
update-interval: 10

# Первый текст и цвет
text1: "Бу!"
color1: "RED"

# Второй текст и цвет
text2: "Сладость или радость"
color2: "LIGHT_PURPLE"
